CREATE TABLE TB_Enfermedades (
    ID_Enfermedad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Enfermedad VARCHAR2(50) NOT NULL UNIQUE
);
    
CREATE TABLE TB_Habitaciones (
    Num_Habitación INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Piso VARCHAR2(20) NOT NULL
);

CREATE TABLE TB_Medicamentos (
    ID_Medicamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Medicamento VARCHAR2(100) NOT NULL,
    Hora_Aplicación VARCHAR2(50) NOT NULL
);

CREATE TABLE TB_Camas (
    Num_Cama INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Num_Habitación INT NOT NULL,
    
    --Constraints------------------

    CONSTRAINT FK_Cama_Habitación FOREIGN KEY (Num_Habitación)
    REFERENCES TB_Habitaciones (Num_Habitación)
);

CREATE TABLE TB_Pacientes (
    ID_Paciente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombres VARCHAR2(50) NOT NULL,
    Apellidos VARCHAR2(50) NOT NULL,
    Edad INT CHECK(Edad > 0) NOT NULL,
    Num_Cama INT NOT NULL,

    --Constraints------------------
    CONSTRAINT FK_Paciente_Cama FOREIGN KEY (Num_Cama)
    REFERENCES TB_Camas (Num_Cama)
);

CREATE TABLE TB_Expedientes (
    ID_Expediente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Paciente INT NOT NULL,
    ID_Enfermedad INT NOT NULL,

    --Constraints-------------------

    CONSTRAINT FK_Expediente_Paciente FOREIGN KEY (ID_Paciente)
    REFERENCES TB_Pacientes (ID_Paciente),

    CONSTRAINT FK_Expediente_Enfermedad FOREIGN KEY (ID_Enfermedad) 
    REFERENCES TB_Enfermedades (ID_Enfermedad)
);

CREATE TABLE TB_Recetas (
    ID_Receta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Medicamento INT NOT NULL,
    ID_Paciente INT NOT NULL,

    --Constraints----------------------

    CONSTRAINT FK_Receta_Medicamento FOREIGN KEY (ID_Medicamento)
    REFERENCES TB_Medicamentos (ID_Medicamento),

    CONSTRAINT FK_Receta_Paciente FOREIGN KEY (ID_Paciente)
    REFERENCES TB_Pacientes (ID_Paciente)
);